### ISSUE TITLE
mega.nz qnap

### ISSUE THREAD

**Issue by rr10** [qnap-dev/qdk2#4]
when a module  for mega.nz ??

Website: https://mega.co.nz/
Description: Encrypted Cloud space, 50GB for free.
Documentation: https://mega.nz/#doc
Source code: https://mega.co.nz/#sync!linux
License: free

**Comment by walkerlee** [comment]
Hi @rr10,

You can do feature request on this forum
https://forum.qnap.com/viewforum.php?f=24&sid=26bb7b830e83a185f560aff10257e846
