### ISSUE TITLE
Unable to extract some QPKGs (unexpected EOF)

### ISSUE THREAD

**Issue by virtualdj** [qnap-dev/qdk2#7]
Hi, I normally build the QPKGs on a QNAP with the [QDK 2.3.3](https://wiki.qnap.com/wiki/QPKG_Development_Guidelines#Downloads) available on the QNAP site.

Unfortunately, there are some of them that I'm **not able to extract** with QDK2:
1. Those with a **compression different from gzip** (apparently QDK2 only supports gzip?)
2. Some others QPKGs that give _tar_ errors at the end, so that QDK2 returns a non-zero exit code

In the second case, this is an example (QPKG can be downloaded from [here](https://www.dropbox.com/s/v2sa5ci0uoxxzob/TVHeadend_0.9.4.2_x86_64.qpkg?dl=1)):
```
root@debian:~/qnap/qdk2/bin#` DEBUG=1 ./qdk2 extract TVHeadend_0.9.4.2_x86_64.qpkg
... cut ...
./bin/libc/librt.so.1
./bin/libc/libresolv.so.2
./bin/libc/tvh-loader
./bin/libc/libgcc_s.so.1
./bin/tvh-rename
./bin/tvheadend

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
[18:14:17][WARNING] Error in extracting: Command '['tar', 'xvf', './data.tar.gz', '-C', './shared']' returned non-zero exit status 2
```
But the same file extracts correctly with QDK 2.3.3 on the QNAP and also installs correctly without any warning messages.
I saw [this line on the sources](https://github.com/qnap-dev/qdk2/blob/74a241828f8e34abd7a80bfdbd9632705e6bcd80/python/qdk2/extract.py#L57), is this problem related to it? Can this be fixed?

**Comment by virtualdj** [comment]
Any news? With the latest git version (dbaeb8ed4) and the same file linked above I still get:
```
./bin/libc/librt.so.1
./bin/libc/libresolv.so.2
./bin/libc/tvh-loader
./bin/libc/libgcc_s.so.1
./bin/tvh-rename
./bin/tvheadend

gzip: stdin: decompression OK, trailing garbage ignored
./.qpkg_icon_gray.gif
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[13:34:20][WARNING] Error in extracting: Command '['tar', 'xvf', './data.tar.gz', '-C', './shared']' returned non-zero exit status 2
```

**Comment by edhongcy** [comment]
Hi @virtualdj 
The reason for gzip decompress warning is 
https://github.com/qnap-dev/QDK/blob/master/shared/bin/qbuild#L947
QDK add flag in data.tar.gz tail.  
But it warning does not affect the content of the data.

PS:NAS gzip is busybox so omit warning message.
